INSERT INTO HEROES (ID, NAME) VALUES (1, 'Narco');
INSERT INTO HEROES (ID, NAME) VALUES (2, 'Bombasto');
INSERT INTO HEROES (ID, NAME) VALUES (3, 'Celeritas');
INSERT INTO HEROES (ID, NAME) VALUES (4, 'Magneta');

